spring:
  datasource:
    url: jdbc:postgresql://juggernauts-db.cnwcxrrmq60v.us-east-1.rds.amazonaws.com:5432/todo?user=postgres&password=xiddy5-fikpor-keZjuv
    driver-class-name: org.postgresql.Driver
