#spring:
#  datasource:
#    #url: jdbc:postgresql://juggernauts-db.cnwcxrrmq60v.us-east-1.rds.amazonaws.com:5432/todo?user=postgres&password=xiddy5-fikpor-keZjuv
#    url: jdbc:postgresql://localhost:5432/todo
#    driver-class-name: org.postgresql.Driver



server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
mailgunUsername: ${MAILGUN_USER:username}
mailgunPassword: ${MAILGUN_PASSWORD:password}
mailgunUrl: ${MAILGUN_URL:https://meow.com}
mailgunFrom: ${MAILGUN_FROM:me <me@ow.com>}