server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:vedzic-mekDi1-wepwuc}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/todo}
    driver-class-name: org.postgresql.Driver
