server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:ColorLink816}
    url: ${DB_URL:jdbc:postgresql://project-2.czqazjmobtc2.us-east-2.rds.amazonaws.com:5432/}
    driver-class-name: org.postgresql.Driver
mailgunUsername: ${MAILGUN_USER:username}
mailgunPassword: ${MAILGUN_PASSWORD:password}
mailgunUrl: ${MAILGUN_URL:https://meow.com}
mailgunFrom: ${MAILGUN_FROM:me <me@ow.com>}
